<?php
return [
    'ID'=>'表ID',
    'User'=>'用户',
    'User ID'=>'用户ID',
    'Supplier ID'=>'供货商ID',
    'Create'=>'新建',
    'Update'=>'修改',
    'Delete'=>'删除',
    'Username'=>'用户名',
    'Password'=>'密码',
    'Search'=>'查询',
    'Reset'=>'重置',
    'VerifyCode'=>'验证码',
    'Portrait'=>'头像',
    'Incorrect username or password'=>'账号或密码错误',
    'Priority'=>'排序(越大越靠前)',
    'Group'=>'分组',
    'Desc'=>'描述',
    'Users'=>'用户列表',
    'Staff Code'=>'用户ID',
    'Name'=>'工作人员姓名',
    'Phone'=>'工作人员电话',
    'Head'=>'头像',
    'Group ID'=>'分组',
    'Group Name'=>'分组名',
    'User Signs'=>'用户签到',
    'Longitude'=>'经度',
    'Latitude'=>'纬度',
    'Image'=>'图片',
    'Domain ID'=>'地区',
    'Department ID'=>'部门',
    'User Supplier'=>'用户和供货商关系',
    'Region'=>'地区',
    'Departments'=>'部门',
    'Rank'=>'级别',
    'User Location'=>'员工定位记录',
    'Shop ID'=>'店铺id',
    'Shop Name'=>'店铺名称',
    'User Indices'=>'个人业务排名详细',
    'Company Reviews'=>'系统设置',
    'Company Categroys'=>'企业注册审核',
    'Update App Version'=>'修改安卓版本信息',
    'Update Ios Version'=>'修改IOS版本信息',
    'Company Interfaces'=>'企业接口列表',
    'Create Company Interfaces'=>'创建企业接口列表',
    'Update Company Interface'=>'修改企业接口列表',
    'Child Company Categroys'=>'子公司列表',
    'Company Interface Modules' => '企业接口列表',
    'User Logs'=>'用户日志',
    'Company Interface Modules' => '企业接口管理',
    'Pay Order' => '提成支付',
    
    
];